name: security-main
on:
  push:
    branches: [ main ]

jobs:
  main-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug list files
        run: ls -la

      - name: Gitleaks
  continue-on-error: true
  run: |
    docker run --rm -v "$PWD":/repo zricethezav/gitleaks:latest \
      detect -s /repo --no-git --redact \
      --report-format sarif -r /repo/gitleaks.sarif || true

- name: Semgrep (OWASP Top 10)
  continue-on-error: true
  run: |
    docker run --rm -v "$PWD":/src returntocorp/semgrep:latest \
      semgrep --config p/owasp-top-ten --sarif -o /src/semgrep.sarif || true

      - name: Trivy filesystem (SARIF)
        run: |
          docker run --rm -v "$PWD":/repo aquasec/trivy:latest \
            fs --format sarif -o trivy-fs.sarif /repo || true

      - name: Build demo image
        run: docker build -t devsecops-demo:${{ github.sha }} .

      - name: Trivy image scan (SARIF)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest \
            image --format sarif -o trivy-img.sarif devsecops-demo:${{ github.sha }} || true

      - name: Checkov IaC (SARIF)
        run: |
          docker run --rm -v "$PWD":/src bridgecrew/checkov:latest \
            -d /src -o sarif > checkov.sarif || true
            
      - name: List reports
  run: ls -lh *.sarif || true
    

      - name: Upload artifacts
  uses: actions/upload-artifact@v4
  with:
    name: main-security-artifacts
    path: |
      gitleaks.sarif
      semgrep.sarif
      trivy-fs.sarif
      trivy-img.sarif
      checkov.sarif
    if-no-files-found: warn

