- name: Gitleaks
  continue-on-error: true
  run: |
    docker run --rm -v "$PWD":/repo zricethezav/gitleaks:latest \
      detect -s /repo --no-git --redact --exit-code 1

- name: Semgrep (strict)
  continue-on-error: true
  run: |
    docker run --rm -v "$PWD":/src returntocorp/semgrep:latest \
      semgrep ci --config p/owasp-top-ten --error --timeout 300
